# Generated by Django 6.0.2 on 2026-03-02 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('supervisor', models.CharField(max_length=150)),
                ('total_required_hours', models.DecimalField(decimal_places=2, default=448, help_text='Total OJT hours required (default 448)', max_digits=6)),
                ('ojt_start_date', models.DateField(help_text='Official OJT start date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('daily_hours', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: (time_out - time_in) - 1hr lunch', max_digits=5)),
                ('week_number', models.PositiveIntegerField(editable=False, help_text='Custom week number based on OJT start date')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='tracker.userprofile')),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('weekly_learnings', models.TextField(blank=True, default='')),
                ('major_tasks', models.TextField(blank=True, default='', verbose_name='Major Tasks Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='tracker.userprofile')),
            ],
            options={
                'verbose_name': 'Weekly Summary',
                'verbose_name_plural': 'Weekly Summaries',
                'ordering': ['week_number'],
                'unique_together': {('profile', 'week_number')},
            },
        ),
    ]
